# Generated by Django 5.0.7 on 2024-08-14 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=8000)),
                ('starting_bid', models.PositiveIntegerField(default=0)),
                ('addition_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('house_garden', 'House & Garden'), ('babies', 'Babies'), ('beauty', 'Beauty'), ('health', 'Health'), ('culture_entertainment', 'Culture and Entertainment'), ('sports_hobby', 'Sports and Hobby'), ('cars', 'Cars'), ('real_estates', 'Real Estates'), ('services', 'Services')], default='electronics', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
