# Generated by Django 5.0.7 on 2024-08-21 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_comment_likes_comment_addition_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='addition_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
